CODE SEGMENT
ASSUME CS: CODE 
ORG 2000H
START:
MOV AL, 0H ;SET
MOV DX, 0FF81H
OUT DX, AL
MOV AL, 32H ;CLOCK
OUT DX, AL
MOV AL, 0DFH ;CLEAR
OUT DX, AL
MOV CX, 0FFH ; DELAY
LP: NOP
LOOP LP
MAIN:
MOV AL, 85H ;SELECT THE FIRST 7-SEDMENT
MOV DX, 0FF81H
OUT DX, AL
MOV AL, 020H ;PRINT G
MOV DX, 0FF80H 
OUT DX, AL
MOV AL, 84H ;SELECT THE 2ND 7-SEDMENT
MOV DX, 0FF81H
OUT DX, AL
MOV AL, 0C0H ;PRINT P
MOV DX, 0FF80H 
OUT DX, AL
MOV AL, 83H ;SELECT THE 3D 7-SEDMENT
MOV DX, 0FF81H
OUT DX, AL
MOV AL, 0F3H ;PRINT -
MOV DX, 0FF80H 
OUT DX, AL
MOV AL, 82H ;SELECT THE 4TH 7-SEDMENT
MOV DX, 0FF81H
OUT DX, AL
MOV AL, 20H ;PRINT 6
MOV DX, 0FF80H 
OUT DX, AL
JMP MAIN
END START
CODE ENDS
