CODE SEGMENT
ASSUME CS:CODE
ORG 2000H
START:
MOV AL, 80H
MOV DX, 0FF2BH ;CWR
OUT DX, AL
MOV AL, 0FFH
MOV DX, 0FF29H ;PORT B
OUT DX, AL
MAIN:
MOV SI, OFFSET ROWS
MOV DI, OFFSET COLS
MOV CX,0
LP:
MOV AL, [SI]
MOV DX, 0FF2AH ;PORT C Indicates the beginning of 
the ROWS ARRAY
OUT DX, AL
MOV AL, [DI]
MOV DX, 0FF28H ;PORT A Indicates the beginning of 
the COLS ARRAY
OUT DX, AL
PUSH CX ;DELAY
MOV CX, 500
DELAYS: NOP
LOOP DELAYS
POP CX
INC DI ; INDICATES NEXT ELEMENT IN COLS ARRAY
INC SI ; INDICATES NEXT ELEMENT IN ROWS ARRAY
INC CX ; NEXT LED
CMP CX, 7 ;CHECK IF IT ARRAIVE 8X8
JE MAIN ; GO TO ELEMENT 0 IN ARRAYS
JMP LP ; COMPLETE
COLS DB 83H, 0FBH, 0F7H, 0CFH, 0BFH, 0BBH, 0C7H 
;NUMBER 2
ROWS DB 01H, 02H, 04H, 08H, 10H, 20H, 40H ;ON
END START
CODE ENDS
